### ISSUE TITLE
Sanity Check

### ISSUE THREAD

**Issue by alexanderbock** [alexanderbock/alexanderbock.github.io#1]
Hey @emiax , @klaseskilson 
could you check whether I didn't make any stupid mistakes?

The files that I have created are:
*.html
images/*
assets/academics.css
assets/academics_presentations.js
assets/academics_publications.css
assets/academics_publications.js
assets/academics_supervision.js
assets/academics_teaching.js
assets/column.css
assets/projects.js
assets/tabular.css

**Comment by emiax** [comment]
Nice website! Going to go through that podcast list one item at the time :)
I reacted to the column.css. There is an issue with columns for small
screens, for example with the links to presentations, supervision etc. You
can look into css media queries to make that look better on phones etc.

**Comment by klaseskilson** [comment]
![great!](https://media.giphy.com/media/JQQwgVUMDIyAM/giphy.gif)

Looks great! 

Some thoughts:

- The width of the page makes the readability suffer some. Try making the text bigger or the site less wide, so that the rows cover fewer words. I'd suggest something around `900px` width on `.container` instead of the `1400px` that it is now, or using a lower column count than 12. This might create some unwanted behaviour on the find-you-on-the-internet links in the footer. 

- <img width="631" alt="screen shot 2017-08-26 at 13 10 59" src="https://user-images.githubusercontent.com/1674076/29743458-7cc0a10c-8a60-11e7-9b78-03f35942834d.png"> The menu looks a bit weird at some display widths. ☝️ 

- The elements in the Academics sub menu varies. Compare index.html and academics.html.

Content related: 

- The elements in the Academics sub menu varies. Compare in index.html and academics.html

- Are the names on the Supervision page correct? "Michael Nielsson & Oskar Carlbaum" -> "Michael Novén & Oskar Carlbaum" and "Michael Novén & Rickard Lindstedt" -> "Michael Sjöström & Rickard Lindstedt"?

**Comment by alexanderbock** [comment]
Thanks both of you!  Fixed all the issues that I could, but using the media queries and turning a horizontal list into a vertical one is too much for my small javascript brain, so it'll have to do ;)
